#!/usr/bin/env python3

import sys
import signal
from signal import SIG_DFL

try:
    def sig_handler(signum, frame):
        print('Exit command mode')
        sys.exit(0)

    signal.signal(signal.SIGINT, sig_handler)
    signal.signal(signal.SIGPIPE, SIG_DFL)
except:
    pass

from advisors.oe_review import main


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Exception as error:
        print("WARNING: Command execution error")
        print(error.message)
        sys.exit(1)
